### ISSUE TITLE
Features for YouTube and bug

### ISSUE THREAD

**Issue by Beastmastah64** [derpierre65/BetterStreamChat#11]
**Features**
- This extension already offers more options and features than [BetterYTG](https://chrome.google.com/webstore/detail/better-youtube-gaming/ioncgheockjakdmpighekmfhdljboimf?hl=en) and it had a bad implementation of Twitch Emotes, so it would be great if you guys added top emotes of BTTV and FFZ and make a option in YouTube chat, where you can open a window to choose emotes like how it works on Twitch and use it easily, unlike BetterYTG.
- Twitch like Theater Mode for YouTube, there is already an [extension ](https://chrome.google.com/webstore/detail/twitch-theater-mode-for-y/emkgicniaaleakbicedgkimdegnjgbkd) exists for this great feature, but would rather have these features on one extension.

**Bug**
- In YouTube, the extension sometimes doesn't work, you can't even see sometimes BetterStreamChat option in top right, like you need to reload the page to make it work and sometimes suddenly it will stop working, the chat will look normal.

**Comment by derpierre65** [comment]
the bug appears in which addon version?

**Comment by Beastmastah64** [comment]
Addon version - 1.2.2
I use Google Chrome - Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by derpierre65** [comment]
the twitch global emotes should be available in chat  
i want remove the BTTV emotes option, because other addons can handle it.

**Comment by derpierre65** [comment]
should be fixed in latest version
