### ISSUE TITLE
Timestamp bug in trovo

### ISSUE THREAD

**Issue by tobiasvasquez** [derpierre65/BetterStreamChat#12]
I can see my timestamp when i send a message, but when a user sends a message, it says aN:aN. 

I'll attach a picture. [
![0a4440d0f450c2706d585e605664e10f](https://user-images.githubusercontent.com/54642010/96358482-035ad280-10de-11eb-944d-bbcd432597e6.png)
](url)

**Comment by derpierre65** [comment]
browser?

**Comment by tobiasvasquez** [comment]
google chrome
