### ISSUE TITLE
Emotes Revert to Text

### ISSUE THREAD

**Issue by Wolvesbane** [derpierre65/BetterStreamChat#16]
When using emotes, they show for a few seconds, then revert back to text until you refresh the page. I'm using version 1.2.2 of BetterStreamChat, on the Opera GX browser.

**Comment by derpierre65** [comment]
youtube or trovo?

**Comment by Wolvesbane** [comment]
> youtube or trovo?

YouTube

**Comment by derpierre65** [comment]
i think it's fixed with latest version.
